### ISSUE TITLE
Rebuild the admin theme

### ISSUE THREAD

**Issue by ringmaster** [habari/habari#387]
The current theme has served us well, and we should keep the good aspects of it (spartan and easy), but it's showing its age and resistance to updates.

We should refactor the theme to be responsive, mobile-friendly, and less reliant on view-embedded logic for operation.  We should capitalize on the strengths of the existing interface.  We should improve the visual appeal of the UI design.
- [ ] #388 Refactor FormUI Templates
- [x] #516 Login Form Styled Differently, Placeholders Broken
- [x] #528 Publish page is unstyled
- [ ] #530 Remove Loupe, Add Filters
