### ISSUE TITLE
Admin area fixes, collection

### ISSUE THREAD

**Issue by Konzertheld** [habari/habari#605]
I'm trying to list all the stuff that needs to be fixed in the 0.10 admin before we can use it in the 0.10 release, including the small things that don't deserve an own ticket. Feel free to add some or link existing tickets.
- [ ] Publish page: Settings tab styling in general and #436 
- [ ] Publish page: Silo styling (they actually work that way, but well), including #328 
- [ ] Publish page buttons #601 
- [x] Manage page: DIsplay of posts without author #635
- [x] Manage page: Search box clearing #28 and URLs #618
- [x] Manage page: Pagination is missing
- [ ] Manage page: AJAX is broken https://github.com/habari/system/commit/b35a3ea0a0325956c84b58eb5459308f323738c5
- [x] Manage page: Use search hints $special_searches (defined in handler but only used in deprecated navigator.php)
- [x] Manage page: Searching for tags is broken #624
- [x] Tags page is missing #596 
- [ ] Options page styling
- [ ] Theme page block section is broken #571 #541 #419 #418 #190 and now non-functional
- [ ] Center dashboard add block icon #595 
- [x] Plugin page: Add FormUI, search does not work (replace it with faceted search?) #628 
- [ ] Plugin page: Configuration styling (e.g. Flickr silo links are not noticable)
- [x] Plugin page: Empty XML file causes errors #404 
- [ ] User page: Search does not work (replace it with faceted search?)
- [ ] User page: Styling improvements (forms)
- [ ] Users page: Limit and paging #327 
- [ ] Profile page styling
- [ ] Groups page: Search does not work (replace it with faceted search?)
- [ ] Groups page: Styling improvements (form)
- [ ] Logs page: Styling improvements (navigation area)
- [ ] Logs page: Navigation does not work
- [ ] Log trimming #457 
- [ ] Sysinfo page cleanup #545
- [ ] Rebuild theme collection #387 
- [ ] Mobile design #230 
- [ ] Inconsistent including of header and footer, should always use theme functions, not include
- [ ] Block titles are not descriptive and UI does not allow them to be #417 
- [ ] Groups page doesn't manage membership well #309
